project:
  type: website
  output-dir: docs
  
website:
  title: "" #"DE's Web site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bio.qmd
      - projects.qmd
      - talks.qmd
      - workshops.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dileepa-ediriweera/
      - icon: github
        href: https://dileepae.github.io/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Dileepa Ediriweera"

format:
  html:
    theme: flatly #cerulean
    toc: true

editor: source

