project:
  type: website
  output-dir: docs
  
website:
  title: "DE's Web site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - talks.qmd
      - workshops.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://dileepae.github.io/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Dileepa Ediriweera"

format:
  html:
    theme: flatly #cerulean
    toc: true

editor: source

